---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
    - port: 5000
      targetPort: 8080
      protocol: TCP
      name: http
---
# Source: microservice/templates/deployment.yaml
apiVersion: v1
kind: Deployment
metadata:
  name: emailservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  emailservice
    template:
      metadata:
        labels:
          app: emailservice
      spec:
        containers:
          - name: emailservice
            image: "gcr.io/google-samples/microservices-demo/emailservice:v0.8.0"
            ports:
            - containerPort: 8080
            env:
            - name: port
              value: "8080"
